// Client-safe slice — NO Prisma imports, NO server-only code.
// Safe to import from Client Components.

import type { ColumnDef } from '@/shared/excel-import/types';

export const assetsImportColumns: readonly ColumnDef[] = [
  {
    header: 'Empresa*',
    key: 'company',
    type: 'string',
    required: true,
    maxLength: 10,
    width: 12,
    example: 'NVH',
  },
  {
    header: 'Categoría*',
    key: 'category',
    type: 'string',
    required: true,
    maxLength: 100,
    width: 25,
    example: 'Computador Portátil',
  },
  {
    header: 'Sede*',
    key: 'location',
    type: 'string',
    required: true,
    maxLength: 100,
    width: 25,
    example: 'Oficina Principal',
  },
  {
    header: 'Bodega',
    key: 'bodega',
    type: 'string',
    required: false,
    maxLength: 100,
    width: 20,
    example: 'Bodega Central',
  },
  {
    header: 'Marca',
    key: 'brand',
    type: 'string',
    required: false,
    maxLength: 100,
    width: 20,
    example: 'Dell',
  },
  {
    header: 'Modelo',
    key: 'model',
    type: 'string',
    required: false,
    maxLength: 100,
    width: 20,
    example: 'Latitude 5540',
  },
  {
    header: 'Número de serie',
    key: 'serialNumber',
    type: 'string',
    required: false,
    maxLength: 100,
    width: 22,
    example: 'SN-12345',
  },
  {
    header: 'Hostname',
    key: 'hostname',
    type: 'string',
    required: false,
    maxLength: 100,
    width: 20,
    example: 'PC-VENTAS-01',
  },
  {
    header: 'Tag',
    key: 'assetTag',
    type: 'string',
    required: false,
    maxLength: 100,
    width: 15,
    example: 'NVH-TAG-001',
  },
  {
    header: 'Procesador',
    key: 'processor',
    type: 'string',
    required: false,
    maxLength: 100,
    width: 22,
    example: 'Intel Core i5-13500',
  },
  {
    header: 'RAM',
    key: 'ram',
    type: 'string',
    required: false,
    maxLength: 50,
    width: 12,
    example: '16GB DDR5',
  },
  {
    header: 'Almacenamiento',
    key: 'storageCapacity',
    type: 'string',
    required: false,
    maxLength: 50,
    width: 18,
    example: '512GB',
  },
  {
    header: 'Tipo almacenamiento',
    key: 'storageType',
    type: 'enum',
    required: false,
    enumValues: ['SSD', 'HDD', 'NVME', 'EMMC'],
    width: 20,
    example: 'SSD',
  },
  {
    header: 'Sistema operativo',
    key: 'operatingSystem',
    type: 'string',
    required: false,
    maxLength: 100,
    width: 22,
    example: 'Windows 11 Pro',
  },
  {
    header: 'Precio de compra',
    key: 'purchasePrice',
    type: 'number',
    required: false,
    width: 18,
    example: '3500000',
  },
  {
    header: 'Moneda',
    key: 'currencyCode',
    type: 'string',
    required: false,
    maxLength: 10,
    width: 10,
    example: 'COP',
  },
  {
    header: 'Vida útil años',
    key: 'usefulLifeYears',
    type: 'number',
    required: false,
    width: 15,
    example: '5',
  },
  {
    header: 'Fecha de compra',
    key: 'purchaseDate',
    type: 'date',
    required: false,
    width: 18,
    example: '2024-01-15',
  },
  {
    header: 'Estado',
    key: 'generalStatus',
    type: 'enum',
    required: false,
    enumValues: ['GOOD', 'REGULAR', 'BAD', 'DAMAGED', 'RETIRED'],
    width: 14,
    example: 'GOOD',
  },
  {
    header: 'Notas',
    key: 'notes',
    type: 'string',
    required: false,
    maxLength: 500,
    width: 30,
    example: 'Asignado al área de ventas',
  },
] as const;

export const assetsImportDisplayName = 'Activos';
export const assetsImportModuleKey = 'assets';
